BASE_IMAGE="library/ubuntu:22.04"
DOCKERFILE="Dockerfile.ubuntu-firefox"
CONTAINER_NAME="ubuntu-container"
BEGIN_PORT=1
END_PORT=65535
BEGIN_ART_PORT=50000
END_ART_PORTS=(50001)
SCANNING_TECHNIQUES=("fetch" "websocket" "xhr")
N_SCANS=1
PARALLEL_SOCKETS=(1 5 10 20 30 40 50 60 70 100 150 200 250)
SOCKET_TIMEOUTS=400
TAG="ubuntu-firefox"


# BASE_IMAGE="mcr.microsoft.com/windows:20H2-amd64"
# DOCKERFILE="Dockerfile.windows-firefox"
# CONTAINER_NAME="win-container"
# BEGIN_PORT=1
# END_PORT=65535
# BEGIN_ART_PORT=50000
# END_ART_PORTS=(50001)
# SCANNING_TECHNIQUES=("fetch" "websocket" "xhr")
# N_SCANS=1
# PARALLEL_SOCKETS=(1 5 10 20 30 40 50 60 70 100 150 200 250)
# SOCKET_TIMEOUTS=400
# TAG="windows-firefox"

# BASE_IMAGE="mcr.microsoft.com/windows:20H2-amd64"
# DOCKERFILE="Dockerfile.windows-chrome"
# CONTAINER_NAME="win-container"
# BEGIN_PORT=1
# END_PORT=65535
# BEGIN_ART_PORT=50000
# END_ART_PORTS=(50100)
# SCANNING_TECHNIQUES=("fetch")
# N_SCANS=1
# PARALLEL_SOCKETS=150
# SOCKET_TIMEOUTS=(150)
# TAG="windows-chrome"

# BASE_IMAGE=library/ubuntu:22.04
# DOCKERFILE="Dockerfile.ubuntu-chrome"
# CONTAINER_NAME="ubuntu-container"
# BEGIN_PORT=1
# END_PORT=65535
# BEGIN_ART_PORT=50000
# END_ART_PORTS=(50100)
# SCANNING_TECHNIQUES=("fetch")
# N_SCANS=1
# PARALLEL_SOCKETS=150
# SOCKET_TIMEOUTS=(150)
# TAG="ubuntu-chrome"

for TECHNIQUE in "${SCANNING_TECHNIQUES[@]}"; do
    for PARALLEL_SOCKET in "${PARALLEL_SOCKETS[@]}"; do
        for END_ART_PORT in "${END_ART_PORTS[@]}"; do
            ./scripts/build-and-run.sh $BASE_IMAGE $DOCKERFILE $CONTAINER_NAME $BEGIN_PORT $END_PORT $BEGIN_ART_PORT $END_ART_PORT $TECHNIQUE $N_SCANS $PARALLEL_SOCKET $SOCKET_TIMEOUTS $TAG
        done
    done
done